### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by brodyxawesome1** [HackerHansen/1v1.YEET-v2#11]
how do make work on real fortnite likei t works but is there a way to not make it flickk to the ground

**Comment by HackerHansen** [comment]
Grab a new color

**Comment by HackerHansen** [comment]
Wait nvm I thought this issue was on another repo of mine, sorry. What do you mean by having it not flick at the ground?

**Comment by brodyxawesome1** [comment]
when ever i aim it flicks to a diffrent poisetion

**Comment by HackerHansen** [comment]
That's weird, there's no aimbot in this. I'm closing this for now since I can't reproduce and this issue shouldn't really be caused by 1v1.YEET
