### ISSUE TITLE
Rapid fire

### ISSUE THREAD

**Issue by Epic99992** [HackerHansen/1v1.YEET-v2#12]
Rapid fire does not work

**Comment by HackerHansen** [comment]
Thanks for bringing this to my attention. 

I just checked, and a lot of stuff is broken. I'll try to roll out a fix by the end of today or tomorrow.

**Comment by Epic99992** [comment]
> Thanks for bringing this to my attention.
> 
> I just checked, and a lot of stuff is broken. I'll try to roll out a fix by the end of today or tomorrow.

Thanks

**Comment by HackerHansen** [comment]
I just updated the trainer, it should work now.
