### ISSUE TITLE
AImbot

### ISSUE THREAD

**Issue by Clqn** [HackerHansen/1v1.YEET-v2#13]
Hey this isnt really an issue but I was wondering if you could maybe add aimbot to the yeet v2 that would be greatly apprecaited if not its okay I tried using your old repo for the color aimbot, tried getting a new color as well same results any help is greatly appreciated

**Comment by HackerHansen** [comment]
I'm not planning on adding aimbot or any new features at the moment. I don't really play the game anymore, so any updates I push out are fixes for the trainer when the game updates. Sorry

**Comment by Clqn** [comment]
All right :)

**Comment by HackerHansen** [comment]
Thank you for understanding lol
