### ISSUE TITLE
Some things no longer work

### ISSUE THREAD

**Issue by Outheblu** [HackerHansen/1v1.YEET-v2#14]
It seems like starting today, God Mode and Rapid Fire are no longer working.

**Comment by HackerHansen** [comment]
Thanks for bringing this to my attention. If I have time I'll try to fix these features tomorrow

**Comment by HackerHansen** [comment]
Oops I forgot about this completely, I'll try to get push the update by next week lol

**Comment by HackerHansen** [comment]
Ok I updated the features, redownload the trainer and it should work now
