### ISSUE TITLE
Godmode

### ISSUE THREAD

**Issue by QwakeIsBest** [HackerHansen/1v1.YEET-v2#17]
Suuuuuuuup, In zone, can you make godmode work in it and could you also make infinint amo and rapid fire 1 thing, thank you thats all, Qwake

**Comment by QwakeIsBest** [comment]
as work in the storm in zone

**Comment by HackerHansen** [comment]
I'll make god mode work in zone soon. 

I'll be keeping infinite ammo and rapid fire separate. Some people only want to use one of the features, and if you want to use both you just have to click an extra button.

**Comment by QwakeIsBest** [comment]
Okay thank you for reading it :)

**Comment by HackerHansen** [comment]
Ok it should work in the zone now, enjoy
