### ISSUE TITLE
ratted me

### ISSUE THREAD

**Issue by nnnewo** [HackerHansen/1v1.YEET-v2#20]
self explanatory ....... the cheat ratted me

**Comment by vanility0001** [comment]
same DOUBLE-U TEE EFF

**Comment by HackerHansen** [comment]
Please actually read the instructions. 

_Cheat Engine tends to bundle useless bundleware, so make sure you read the installation window and make sure you are installing only Cheat Engine and not anything else if you don't want bundleware._
