### ISSUE TITLE
Casual zombie mode does not work

### ISSUE THREAD

**Issue by Devaansh-Pathak** [HackerHansen/1v1.YEET-v2#21]

**Comment by HackerHansen** [comment]
Can you explain the problem a little more lol

**Comment by Devaansh-Pathak** [comment]
First I played box 2v2 with my friend to prank him then I went in zombie mode and started using rapid fire but zombies were not dying

**Comment by HackerHansen** [comment]
> First I played box 2v2 with my friend to prank him then I went in zombie mode and started using rapid fire but zombies were not dying

This is a problem with God Mode. It makes zombies invincible too when you have it on. Unfortunately, I probably won't be fixing this though since it's only a PvE problem.
