### ISSUE TITLE
Update plz

### ISSUE THREAD

**Issue by QwakeIsBest** [HackerHansen/1v1.YEET-v2#22]
Could you make something that changes the amount of lol coins you have + could you make speed hack work on chrome

**Comment by Xemply** [comment]
Yea that would be good

**Comment by QwakeIsBest** [comment]
yeah the hack is kinda getting boring

**Comment by Xemply** [comment]
True

**Comment by HackerHansen** [comment]
> Could you make something that changes the amount of lol coins you have + could you make speed hack work on chrome

I'm pretty sure lol coins are server sided, so a currency hack likely isn't possible. 

I can probably make speedhack work for chrome sometime soon, but that's only if the default cheat engine speedhack works. 

As for adding extra features, I probably won't do that soon. I barely play this game anymore so updates from now on will probably just be fixes for when the cheat breaks when the game updates. 

If I ever do feel like playing the game a lot again then I'll probably either add new features or make v3 (I don't know if or when this will happen). 

I'll leave this issue open until I either made speedhack work for chrome or I confirmed that it isn't possible.

**Comment by Xemply** [comment]
Ok

**Comment by QwakeIsBest** [comment]
hey, just saying I did some testing with the speed hack and the default from cheat engine doesn't work

**Comment by HackerHansen** [comment]
> hey, just saying I did some testing with the speed hack and the default from cheat engine doesn't work

Oh nvm then, it won't work
