### ISSUE TITLE
rapid fire

### ISSUE THREAD

**Issue by nobleshinobiyt** [HackerHansen/1v1.YEET-v2#23]
hi actually i have been using this 1v1.lol hacks every hack is very useful and all of them are working except one the rapid fire one that hack is not working plz look into it!

**Comment by QwakeIsBest** [comment]
same its not working for me either, it works for my friend. try making a new one hackerHansen with diff address or someting like that

**Comment by HackerHansen** [comment]
I'll probably fix this during the weekend

**Comment by HackerHansen** [comment]
I fixed it, sorry it took so long. I kinda forgot about it earlier lol

**Comment by nobleshinobiyt** [comment]
hahaha lol thanxxxx!!!!!
