### ISSUE TITLE
God Mode not working in Both Firefox and Chromium based Browsers

### ISSUE THREAD

**Issue by MathsJarviz** [HackerHansen/1v1.YEET-v2#28]
After the new update in 1v1.lol, God mode is not working on both the browsers.
Please consider my issue and fix it quickly

**Comment by HackerHansen** [comment]
> After the new update in 1v1.lol, God mode is not working on both the browsers.
> Please consider my issue and fix it quickly

Thanks for letting me know. I'll fix it eventually, I don't know about the "quickly" part though, I'll just fix it when I have time to kill. I'll let you know once it's done.

**Comment by HackerHansen** [comment]
Ok I fixed it, redownload it and it should work

**Comment by MathsJarviz** [comment]
Thank you Sent from Mail for Windows From: HackerHansenSent: 01 December 2021 06:36To: HackerHansen/1v1.YEET-v2Cc: MathsJarviz; AuthorSubject: Re: [HackerHansen/1v1.YEET-v2] God Mode not working in Both Firefox and Chromium based Browsers (Issue #28) Ok I fixed it, redownload it and it should work—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MathsJarviz** [comment]
Thanks
