### ISSUE TITLE
godmode not working

### ISSUE THREAD

**Issue by koil123457da** [HackerHansen/1v1.YEET-v2#29]
god mode needs a fix it doesn't work anymore but everything else is perfect

**Comment by HackerHansen** [comment]
> god mode needs a fix it doesn't work anymore but everything else is perfect

Thanks for letting me know, I'll take a look when I have time

**Comment by koil123457da** [comment]
thank u

**Comment by HackerHansen** [comment]
I just checked and it still works for both Firefox and Brave. Try refreshing the tab and/or switching to one of these browsers (I recommend Firefox since it supports the most features). There does seem to be an issue with self-destruct on Firefox, though, so I will be fixing that.

**Comment by koil123457da** [comment]
thank u yeah i have been using firefox its great i will try it now

**Comment by koil123457da** [comment]
i tried it i still wont work do u recommend any thing else

**Comment by koil123457da** [comment]
oh wait ill download it again

**Comment by koil123457da** [comment]
its working thank u so much

**Comment by HackerHansen** [comment]
> its working thank u so much

Np, I'm glad it works for you now
