### ISSUE TITLE
Cheat-Engine freezes

### ISSUE THREAD

**Issue by YourActualMum** [HackerHansen/1v1.YEET-v2#3]
If i wanna attach the process it just stop responding.
I have tried it manually a n d with firefox.
Still having the issue.

**Comment by HackerHansen** [comment]
Do command prompt windows open briefly when you click attach?

**Comment by YourActualMum** [comment]
Ye

**Comment by HackerHansen** [comment]
How long does it freeze for? On some computers it might freeze for a few minutes while scanning.

**Comment by YourActualMum** [comment]
It just freeze. I have to close it

**Comment by HackerHansen** [comment]
How long do you wait before you close it?

**Comment by YourActualMum** [comment]
The longest I waited for was like 20 mins

**Comment by HackerHansen** [comment]
That's weird. Does the progress ever go up?

**Comment by YourActualMum** [comment]
No it didn‘t. Also, if I try to attach manually it says I have entered a wrong PID, but I entered the right ohne. Lol

**Comment by HackerHansen** [comment]
Are you sure 1v1.lol is the only tab open?

**Comment by YourActualMum** [comment]
Yes. I tried so many things

**Comment by HackerHansen** [comment]
That's really weird.

**Comment by HackerHansen** [comment]
Normally I never do discord support, but add my alt IgotdemMONEY#9500 on discord (reply here with your username once you've added me, I'll delete these two comments so I don't get spammed by a bunch of people)

**Comment by Provincianoo** [comment]
The exact same thing happened to me

**Comment by HackerHansen** [comment]
I have been unable to reproduce this issue so idk how to fix it, sorry. I'll close this issue for now
