### ISSUE TITLE
God mode

### ISSUE THREAD

**Issue by HackerHansen** [HackerHansen/1v1.YEET-v2#31]
I accidentally deleted the other issue, opening one here for the time being

**Comment by bleu1234** [comment]
it not working

**Comment by HackerHansen** [comment]
I'll fix it later, idk I'm kinda busy lately maybe sometime within like 1-2 weeks cuz I have finals

**Comment by RitzYouTube** [comment]
Ok good luck with ur finals, and never take this down, you are a god among men for making this, have a great day!

**Comment by HackerHansen** [comment]
> Ok good luck with ur finals, and never take this down, you are a god among men for making this, have a great day!

Thanks man

**Comment by trexkhan1** [comment]
when will it be done man

**Comment by HackerHansen** [comment]
> when will it be done man

Idek at this point, this issue has been open for over a month now and I still haven't started 

I'll just do it when I'm bored idk

**Comment by mxlouka** [comment]
> > when will it be done man
> 
> Idek at this point, this issue has been open for over a month now and I still haven't started
> 
> I'll just do it when I'm bored idk

when will you get bored tho?

**Comment by khaledmoayad** [comment]
this guy must be living his best life. He's not getting bored at all

**Comment by HackerHansen** [comment]
Fixed, closing
