### ISSUE TITLE
nothing is working the script but only fast mode is working

### ISSUE THREAD

**Issue by trexkhan1** [HackerHansen/1v1.YEET-v2#35]
pls help so basically what happend was i downloaded it and try to use it but it wont work pls guys can you help with this issue

**Comment by HackerHansen** [comment]
> pls help so basically what happend was i downloaded it and try to use it but it wont work pls guys can you help with this issue

Which browser are you using, and which version of Cheat Engine are you on?

**Comment by HackerHansen** [comment]
> firefox

Can you also answer the second part of the question lmao

**Comment by trexkhan1** [comment]
i think it was the latest one

**Comment by trexkhan1** [comment]
the one that came yesterday

**Comment by HackerHansen** [comment]
> the one that came yesterday

Can you tell me the specific version though? I wanna make sure lol

**Comment by Blazeolmo** [comment]
>asks what browser and version of cheat engine was used
>demands the specific version
>refuses to elaborate further
>leaves

**Comment by HackerHansen** [comment]
Oh shit I don't think I got the response notification 2 months ago, sorry lmfao 

At this stage, 90% of the cheat is broken and I don't plan on fixing it anytime soon. I might just archive the repo at this point tbh, I don't find it fun maintaining this anymore

**Comment by HackerHansen** [comment]
Fixed, closing
