### ISSUE TITLE
Invalid PID

### ISSUE THREAD

**Issue by Charmantroll** [HackerHansen/1v1.YEET-v2#5]
Oops, it seems like you entered an invalid PID!. I put the pid whit most ram usage, and it fail. i tried in opera, firefox, chrome and brave.

**Comment by HackerHansen** [comment]
There seems to be an issue with getting memory usage via command prompt for some people. I might push an update later which gets memory usage directly within the program, which should fix this.

**Comment by Charmantroll** [comment]
Yes, please, I want to troll my friends

**Comment by HackerHansen** [comment]
I pushed an update, it should be fixed now
