### ISSUE TITLE
issues on brave

### ISSUE THREAD

**Issue by astella6969** [HackerHansen/1v1.YEET-v2#6]
im getting this error

Error:[string "attachmentmode = 1
..."]:381: attempt to compare number with nil

im entering the pid that uses most ram though it also doesnt work on firefox which is weird

**Comment by kikiex** [comment]
Same: "Error:[string "attachmentmode = 1
..."]:224: attempt to compare number with nil"
When using Auto, and:Error:"[string "attachmentmode = 1
..."]:224: attempt to compare number with nil
Error:[string "attachmentmode = 1
..."]:381: attempt to compare number with nil"
On manual

**Comment by HackerHansen** [comment]
Its an issue with getting memory usage on some computers, I'll probably roll out a fix later

**Comment by astella6969** [comment]
so is it gonna get fixed or no

**Comment by HackerHansen** [comment]
> so is it gonna get fixed or no

Eventually lol

**Comment by HackerHansen** [comment]
I pushed an update, it should be fixed now
