### ISSUE TITLE
features dont work

### ISSUE THREAD

**Issue by astella6969** [HackerHansen/1v1.YEET-v2#8]
well the title says it, I'm on brave btw and windows 8.1 if that info is required

**Comment by HackerHansen** [comment]
Are you using the latest version? I pushed an update yesterday, try redownloading it

**Comment by astella6969** [comment]
yes i am and i tried to redownload it

**Comment by HackerHansen** [comment]
You probably put in the wrong PID. Is 1v1.lol the only tab open? 

Try using auto mode with Firefox if nothing works

**Comment by astella6969** [comment]
the tab is open and no i didnt i tried the auto mode with firefox it also didnt work

**Comment by HackerHansen** [comment]
If it's not the only tab open it likely won't work. Also make sure the game is fully loaded before you attach
